common:
  save_interval: 2
  test_interval: 5
  log_interval: 100
  max_epoch: 100
  seed: 3401
  amp: False

datasets:
  train_csv_path: '/mnt/lustre/sjtu/home/zkn02/train_encodec/datasets/libritts_train100h.csv'
  test_csv_path: '/mnt/lustre/sjtu/home/zkn02/train_encodec/datasets/LibriTTS_dev-other.csv'
  batch_size: 12
  tensor_cut: 72000
  num_workers: 4
  fixed_length: 0
  pin_memory: True

checkpoint:
  resume: False
  checkpoint_path: ''
  disc_checkpoint_path: ''
  save_folder: './checkpoints/'
  save_location: '${checkpoint.save_folder}/bs${datasets.batch_size}_cut${datasets.tensor_cut}_length${datasets.fixed_length}_' 

optimization:
  lr: 3e-4
  disc_lr: 3e-4

lr_scheduler:
  warmup_epoch: 5

model:
  target_bandwidths: [1.5, 3., 6., 12., 24.]
  sample_rate: 24_000
  channels: 1
  train_discriminator: True # you can set it to 2/3 and other number to train discriminator only
  audio_normalize: True
  filters: 32
  ratios: [8, 5, 4, 2]
  disc_win_lengths: [1024, 2048, 512]
  disc_hop_lengths: [256, 512, 128]
  disc_n_ffts: [1024, 2048, 512]
  causal: True
  norm: 'weight_norm'
  segment: None
  name: 'my_encodec'

distributed:
  data_parallel: True
  world_size: 4
  find_unused_parameters: False
  torch_distributed_debug: False
  init_method: tcp

balancer:
  weights:
    l_t: 0.1
    l_f: 1
    l_g: 3
    l_feat: 3


